/**
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

 */

import {assert} from 'chai'

import evenFibonacciSum from './evenFibonacciSum'

describe('Even fibonacci numbers', () => {
    it('should find the sum of the even-valued members of fibonacci under 4million',
        () => {
            const actual = evenFibonacciSum(4000000)
            const expected = 4613732

            assert.equal(actual, expected)
        })
})
